name: Production Build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Gatsby Build
        run: npm run build

      - name: zip build resulit
        run: tar -czvf build.tar.gz public

      - name: archive zip
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar.gz
  
  deploy:
    needs:
      - build

      steps:
        - name: download artifact
          uses: actions/download-artifact@v2
          with:
            name: build

        - name: extract build
          run: tar -xzvf build.tar.gz

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Deploy to S3
          run: aws s3 sync ./public s3://${{ AWS_PRODUCTION_BUCKET_NAME}} --acl public-read
